<a href="https://colab.research.google.com/github/lisawermers/MAT421/blob/main/MAT421ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.1 Introduction
**Sets:** Collection of objects denoted by: {}

**Union:** A U B - The set containing *all* elements of A and B

**Intersecttion:** A n B - The set containing all elements thats belong to *both* A and B

**Natural Numbers:** N = {1,2,3,4,..}

**Whole Numbers:** W = N U {0}

**Integers:** Z = W U {-1,-2,-3,....}

**Rational Numbers:** Q = { p/q | p ∊ Z , q ∊ Z \ {0}}

**Irrational Numbers:** I = the set of real numbers that can't be expressed as a fraction of integers

**Real Numbers:** (the union of all rational and irrational numbers) R = Q U I

**Complex Numbers:** C = {a + bi | a, b ∊ R, i = sqrt(-1) }

#1.2 Elements of Linear Algebra
**Linear Subspace:** A linear subspace of V is a subset U ⊆ V that is closed under vector addition and scalar multiplication. Meaning, for all u1, u2 ∊ U and a ∊ R: u1 + u2 ∊ u and a*u1 ∊ u

**Span:** let w1,w2,...,wm ∊ V. The span, denoted span(w1,...,wm), is the set of all linear combinations of wi.

Every span is a linear subspace. AKA, let W = span(w1,w2,...,wm). Then W is a linear subspace.

In [1]:
import numpy as np
x = np.array([[1, 3, 1]])
z = np.array([[4, 2, 2]])
print(np.cross(x, z))

[[  4   2 -10]]


**Column Space:** Let A ∊ R^(nxm) be an nxm matrix with columns a1,a2,...,am ∊ R^n. The column space of A, denoted col(A) is the span of all the columns of A.

**Linear Independence:** A list of column vectors u1,u2,...,um is linearly independent if none of them can be written as a linear combination of the other column vectors. 

**Dimension Theorem:** Let U be a linear subspace of V. Any basis of U has the same number of elements, so all bases of U have the same length and same number of elements. That's denoted dim(U).

**Orthonormal:** A list of vectors {u1,...,um} is orthonormal if the u's are pairwise orthogonal and each has a norm = 1 .

**Orthogonal Projection:** Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm. The orthogonal porjection of v ∊ V on U is Pu v = sum(j=1)< v , qj > qj.

**Best Approximation Theorem:** Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm let v ∊ V. For any u ∊ U. ||v-Pu v|| <= ||v-u||.

**Pythagorean Theorem:** Let u1 v ∊ V be orthogonal. Then ||u + v||^2 = ||u||^2 + ||v||^2

**Cauchy-Schwarz:** For any u1 v ∊ V , |<u,v>| <= ||u|| ||v||

**Gram-Schmidt:** Let a1,...,am in R^n be linearly independent. Then there exists an orthonormal basis, q1,...,qm of span(a1,...,am).

**Eigenvalues and Eigenvectors:** Let A ∊ R^(dxd) be a square matrix. Then 𝜆 ∊ R is an eigenvalue of A if there exists a non-zero vector x != 0 such that Ax = 𝜆x. Vector x is an eigenvector.

In [2]:
import numpy as np
from numpy.linalg import eig
x = np.array([ [1, 2], [4, 6] ])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [-0.27491722  7.27491722]
E-vector [[-0.84324302 -0.3036773 ]
 [ 0.53753252 -0.95277495]]


**Diagonal and Similar Matrices:** Let A be similar to a matrix D = diag(𝜆1,...,𝜆d) with distinct diagonal entries, that exists a non-singular matric A such that A = PDP^-1

If A is symmetric, then any 2 eigenvectors from different eigenspaces are orthogonal.

**The Spectral Theorem of Symmetric Matrices:** A nxn symmetric matrix A has the following properties:

- A has n eigenvalyes, counting multiplicities.

- If 𝜆 is an eigenvalues of A with multiplicity k, then the eigenspace for x is k-dimensional.

- The eigenspaces are mutually orthogonal, in the sense that eigenvectors corresponding to different vaues are orthogonal.

- A is orthogonally diagonalizable.

#1.3 Linear Regression
**QR Decomposition:** a useful procedure to solve the linear least square problem using Gram-Schmidt.

In [3]:
import numpy as np
from numpy.linalg import qr
x = np.array([[0, 2], [2, 3]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

z = np.dot(Q, R)
print('QR:', z)

iterations = [1, 20]
for i in range(20):
    Q,R = qr(x)
    x = np.dot(R, Q)
    if i+1 in iterations:
        print(f'Iteration {i+1}:')
        print(x)

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]]
Iteration 1:
[[3. 2.]
 [2. 0.]]
Iteration 20:
[[ 4.00000000e+00  9.09484250e-12]
 [ 9.09494702e-12 -1.00000000e+00]]


**Normal Equations:** Let A ∊ R^(nxm) be an nxm matrix with linearly independent columns and let b ∊ R^n be a vector. The solution to the least-squares problem min||Ax-b|| satisfies A^T Ax = A^T b which are known as the normal equations.

**Least Squares via QR:** Let A ∊ R^(nxm) be an nxm matrix with linearly independent column, let b ∊ R^n be a vector and let A = QR be a QR decomposition of A where Q is a R^(nxm) matrix with Q^T Q = I(mxm) and T is an upper triangle. \